export const API_URLS = {
    login: "auth/login",
    createCollge:"auth/register",
    planApi:"auth/get-plans",
    course:"auth/course-api",
    batch:"auth/batch-api",
    department:"auth/department-api",
    designation:"auth/designation-api",
    addEmployee:"auth/add-employee",
    teacherAllocation:"get-teacher-allocation-field/",
    addteacherallocation:"Add-teacher-allocation/",
    addSubject:"add_subject_api/",
    assignSubject:"assign-subject/",
    getSubjectAllocation:"get-subject-allowcation-field/",
    SubjectAllocation:"subject-allowcation/",
    getElectiveSubject:"get-elective-subject-field/",
    addElectiveSubject:"add-elective-subject/",
    lectureApi:"lecture-plan/",
    roomApi:"addroom-api/",
    getTimeTable:"get-settimetable-field/",
    setTimeTable:"settimetable-api/",
    activetimetable:"active-timetable-api/",
    AddVehciles:"add-vehicle-api/",
    AddDriver:"add-driver-api/",
    AddCategory:"student-category-api/",
    AddDocument:"student-document-api/",
    studentAdmission:"student-admission-api/",
    payType:"auth/paytype-api",
    payableType:"auth/paymenttype-api",
    salarySetting:"auth/salarysetting-api",
    attendance:"attendance-api/",
    EmployeeAttendance:"auth/employee-attendance-api",
    EmployeePayroll:"auth/get-employee-attendance-api",
    EmployeePaySlipGenerationApi:"auth/employee-payslip-api",
    leavetypeapi:"leavetype-api/",
    leaveRequestApi :"leave-api/",
    addRoute :"add-root-api/",
    AddDestination :"destination-api/",
    getCollegeDetails :"auth/get-college/",
    feesStructure:"feestructure-api/",
    employeeLogin:"auth/login-employee"
}
